lists/urls.py
from django.urls import path
from lists.views import view_list
from lists.views import new_list


urlpatterns = [
    path('<list_id>/', view_list, name='view_list'),
    path('new', new_list, name='new_list'),
]

superlists/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from lists.views import home_page
from lists.views import view_list
from lists.views import new_list


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    path('lists/<list_id>/', view_list, name='view_list'),
    path('lists/new', new_list, name='new_list'),
]

lists/models.py
from django.db import models
from django.urls import reverse


class List(models.Model):

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])


class Item(models.Model):
    text = models.TextField(default='', blank=False)
    list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

lists/forms.py
from django import forms
from django.core.exceptions import ValidationError
from lists.models import Item

EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"


class ItemForm(forms.models.ModelForm):
    class Meta:
        model = Item
        fields = ('text',)
        widgets = {'text': forms.fields.TextInput(
            attrs={'placeholder': 'Enter a new to-do item', 'class': 'form-control input-lg', }), }
        error_messages = {'text': {'required': EMPTY_ITEM_ERROR}}

    def save(self, for_list):
        self.instance.list = for_list
        return super().save()


class ExistingListItemForm(ItemForm):
    def __init__(self, for_list, *args, **kwargs):
        super(ExistingListItemForm, self).__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    def save(self):
        return forms.models.ModelForm.save(self)

lists/views.py
from django.core.exceptions import ValidationError
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from lists.models import Item, List

from lists.forms import ItemForm, ExistingListItemForm, EMPTY_ITEM_ERROR


def home_page(request):
    return render(request, 'index.html', {'form': ItemForm()})


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, 'list.html', {'list': list_, "form": form})


def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List.objects.create()
        form.save(for_list=list_)
        return redirect(list_)
    else:
        return render(request, 'index.html', {'form': form, })

lists/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>To-Do lists</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/static/base.css" rel="stylesheet" />
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3 jumbotron">
          <div class="text-center">
            <h1>{% block header_text %}{% endblock %}</h1>
            <form method="POST" action="{% block form_action %}{% endblock %}">
              {{ form.text }} {% csrf_token %} {% if form.errors %}
              <div class="form-group has-error">
                <div class="help-block">{{ form.text.errors }}</div>
              </div>
              {% endif %}
            </form>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          {% block table %} {% endblock %}
        </div>
      </div>
    </div>
    <script src="/static/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="/static/list.js"></script>
    <script>
      $(document).ready(function () {
        window.Superlists.initialize();
      });
    </script>
  </body>
</html>

lists/templates/index.html
{% extends 'base.html' %}
</head>

<body>
  <h1>{% block header_text %}Start a new To-Do list{% endblock %}</h1>
  <form method="POST" action="{% block form_action %}{% url 'new_list' %}{% endblock %}">
    <input name="text" id="id_text" placeholder="Enter a to-do item" />
    {% csrf_token %}
  </form>
</body>

lists/templates/list.html
{% extends 'base.html' %}
  <body>
    <h1>{% block header_text %}Your To-Do list{% endblock %}</h1>
    <form method="POST" action="{% block form_action %}{% url 'view_list' list.id %}{% endblock %}">
      <input
        name="text"
        id="id_text"
        placeholder="Enter a to-do item"
      />
      {% csrf_token %}
    </form>
    {% block table %}
    <table id="id_list_table" class="table">
      {% for item in list.item_set.all %}
      <tr>
        <td>{{ forloop.counter }}: {{ item.text }}</td>
      </tr>
      {% endfor %}
    </table>
    {% endblock %}
  </body>